version: '3'
services:
  nginx:
    build: docker/nginx
    container_name: nginx.${APP_NAME}
    depends_on:
      - php-fpm
    volumes:
      - .:/app
      - ./docker/nginx/vhost:/etc/nginx/conf.d
    ports:
      - '${NGINX_HTTP_PORT}:80'
      - '${NGINX_HTTPS_PORT}:443'
  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm.${APP_NAME}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - ./docker/php-fpm/config/php.ini:/usr/local/etc/php/php.ini
  postgres:
    build: docker/postgres
    container_name: postgres.${APP_NAME}
    env_file: docker/postgres/env/localhost.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/config/localhost.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  redis:
    build: docker/redis
    container_name: redis.${APP_NAME}
    volumes:
      - ./docker/redis/data:/data
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
