version: '3'
services:
  nginx:
    build: docker/nginx
    container_name: nginx.${APP_NAME}
    depends_on:
      - php-fpm
    ports:
      - '${APP_PORT}:80'
      - '443:443'
    volumes:
      - ./docker/nginx/vhost:/etc/nginx/conf.d
      - .:/app
  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm.${APP_NAME}
    volumes:
    - ./docker/php-fpm/config:/usr/local/etc/php
    - .:/app
